version: "3"
services:
  postgresql:
    restart: always
    image: postgres
    hostname: postgresql
    env_file:
      - .env
    container_name: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    depends_on:
      - pgadmin

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    env_file:
      - .env
    container_name: ${PGADMIN_NAME}
    ports:
      - "8080:${PGADMIN_PORT}"
    depends_on:
      - postgresql

volumes:
  postgres:
