version: "3"
services:
  postgresql:
    image: postgres
    env_file:
      - .env
    container_name: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - dbdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    container_name: "${PGADMIN_NAME}"
    ports:
      - "8080:${PGADMIN_PORT}"

volumes:
  dbdata:
